name: Waypoint
main: me.pirogoeth.Waypoint.Waypoint
version: 1.4
author: pirogoeth
commands:
    wp:
        description: Manage waypoints for yourself.
        usage: /wp <add|del|tp;list> [name]
        alias: waypoint
        permission: waypoint.basic
    home:
        description: Save your home location.
        usage: /home [add]
        alias: home
        permission: waypoint.home
    spawn:
        description: Teleport to world spawn points.
        usage: /wpspawn <world>
        permission: waypoint.spawn
    spawnadmin:
        description: Manage spawn details.
        usage: /wpspawnadmin <save|load;set> [world]
        permission: waypoint.admin.spawn
    tp:
        description: Teleport to another user/another user to you.
        usage: /tp <user> [target]
        alias: wptp
        permission: waypoint.teleport
    tphere:
        description: Teleport a user to you.
        usage: /tphere <user>
        alias: wptphere
        permission: waypoint.teleport.here