name: Waypoint
main: me.pirogoeth.Waypoint.Waypoint
version: 1.3
author: pirogoeth
commands:
    wp:
        description: Manage waypoints for yourself.
        usage: /wp <add|del|tp;list> [name]
        alias: waypoint
        permission: waypoint.basic
    home:
        description: Save your home location.
        usage: /home [add]
        alias: home
        permission: waypoint.home