name: Waypoint
main: me.pirogoeth.Waypoint.Waypoint
version: 1.4
author: pirogoeth
commands:
    wp:
        description: Manage waypoints for yourself.
        usage: /wp <add|del|tp;list> [name]
        aliases: 
            - waypoint
        permission: waypoint.basic
    home:
        description: Save your home location.
        usage: /home [add]
        aliases: 
            - home
        permission: waypoint.home
    spawn:
        description: Teleport to world spawn points.
        usage: /spawn <world>
        aliases:
            - wpspawn
        permission: waypoint.spawn
    spawnadmin:
        description: Manage spawn details.
        usage: /spawnadmin <save|load;set> [world]
        aliases:
            - wpspawnadmin
        permission: waypoint.admin.spawn
    warp:
        description: Manage public warps.
        usage: /warp <add|del|set|list|<or warpname>> <warpname or key:value>
        aliases:
            - wpwarp
        permission: waypoint.warp
    tp:
        description: Teleport to another user/another user to you.
        usage: /tp <user> [target]
        aliases: 
            - wptp
        permission: waypoint.teleport
    tphere:
        description: Teleport a user to you.
        usage: /tphere <user>
        aliases: 
            - wptphere
        permission: waypoint.teleport.here